### PR TITLE
Upgrading Json.NET to version 7.0.1.

### PR DESCRIPTION
**Pull request by jbparker**
Hey @jaymedavis 
Splitting this and another into separate pull requests per your request to keep these distinct.

I ran the MSpec tests from CLI and they all passed with my test stripe account.  Let me know what you think / what else I need to change as this is my first PR to the library.

Thanks!

### CODE REVIEW

**Comment by jaymedavis** [comment]
Thanks for contributing! I will get to this as soon as I can. :)

**Comment by jbparker** [comment]
Thanks!

**Comment by jaymedavis** [comment]
Was there any particular benefit from updating, or just updating?

**Comment by jbparker** [comment]
We use a Newtonsoft internally on a project and have several other libraries that have it as a dependency, and not having it updated forces binding redirects which isn't preferable.  Also, just saw that it was updated a few times before so was hoping it wouldn't be an issue.

Sent from Outlook




On Sun, Sep 13, 2015 at 12:58 PM -0700, "Jayme Davis" <notifications@github.com> wrote:
Was there any particular benefit from updating, or just updating?

---

**Comment by jaymedavis** [comment]
Oh yeah, totally not a big deal (and good to do). I was just curious. I would have done this today, but I need to update ReSharper so I can run all the tests first. I'll get it updated pretty soon.

**Comment by jbparker** [comment]
Thanks!—Reply to this email directly or view it on GitHub.

**Pull request closed without merging**
