### PR TITLE
Added statement descriptor to stripe charge.

### PR DESCRIPTION
**Pull request by x3igh7**
This is a helpful field that can describe what stripe plan is being charged against.

### CODE REVIEW

**Comment by lancefisher** [comment]
These changes look good to me. I've been wanting access to the StatementDescriptor that Stripe returns as well. @jaymedavis Does anything need to be done on this before it can be merged? I'm happy to help.

**Comment by jaymedavis** [comment]
Looks good to me, I wish I could just hit the big green button, but I still need to bump the version and publish to nuget as well. You could figure out how to automate that :D

**Comment by jaymedavis** [comment]
I just had to get it pulled in and tested and bump the build. This is merged, I'll be releasing at some point today. Thanks!

**Comment by lancefisher** [comment]
Awesome! Thanks, @jaymedavis!

**Comment by x3igh7** [comment]
Thanks for the merge @jaymedavis

**Comment by jaymedavis** [comment]
Thank YOU! :+1:

**Pull request closed without merging**
