### PR TITLE
Updated StripeAccount; Added StripeManagedAccount and related classes

### PR DESCRIPTION
**Pull request by drewid**
1) Updated StripeAccount with the Account properties Stripe currently supports.

2) Added StripeManagedAccount, which inherits StripeAccount and only contains properties specific to managed accounts.

3) Created the additional classes necessary to support the new properties in StripeManagedAccount

4) Created placeholder services files for ManagedAccounts

### CODE REVIEW

**Comment by drewid** [comment]
I followed the naming conventions being used 100% as much as possible.  I see another pull request which does not maintain the same coding or naming conventions.

**Comment by jaymedavis** [comment]
From a quick glance, this looks great. Tests would be nice, but thanks much for your work. I will get to this asap

**Comment by drewid** [comment]
I am tweaking things a little bit and doing more validation.  For services you would call either StripeAccountService or StripeManagedAccountService for clarity.  Each service would use their corresponding entity for clarity.

**Comment by drewid** [comment]
Additional Account and Managed Account Cleanup 

Cleaned up and tightened up the related code in entities and added the
code in services for Accounts and Managed Accounts.  Minor edits in
other files for consistency.

Will make smaller commits in the future - most of it was all related so harder to separate out since it is all related functionality to get managed accounts up and running

**Comment by jaymedavis** [comment]
Thanks for all your work.

**Comment by jd-alexander** [comment]
Has this been merged with main branch? in need of this feature ASAP. Great work btw. :+1:

**Comment by drewid** [comment]
Thanks. Embarrassed to say but not sure how to the pull process really works.  I have not merged changes back into my main branch, does that need to be done first?  Not sure how.

I also need this ASAP thus did some heavy lifting on it.

The only part I am unsure of is on ExternalAccouts, where you could have a BankAccount or Card as an object. That would need to be a later commit.

**Comment by jd-alexander** [comment]
@drewid Yes. There's a button here that allows you to merge.Once that's done his code becomes apart of your main branch and then you can have a new release of the library with the updated features :smile:

pullrequest-mergebutton

For more details visit this link  : https://help.github.com/articles/merging-a-pull-request/

**Comment by drewid** [comment]
Sorry - I was meaning merging my branch into my main branch fork (or is that not necessary?)

**Comment by jd-alexander** [comment]
No that's not necessary.

**Comment by Giovani-Brady** [comment]
Actually @drewid seeing as the release movement of this repo is particularly slow I'm sure many users, myself included, would really appreciate you merging this into your own fork so this feature is available.

**Comment by jaymedavis** [comment]
you are fine @drewid. nothing else needs to be done.  clicking merge is not the entire story for OSS, as that can bring in unexpected bugs. most people that think this is the only thing involved don't actually run any OSS of their own. you have to verify the code, review it, test it, and make sure the quality is up to speed (it's easy to miss things when you don't know the entire repo)

there is a reason stripe.net has had very few bugs in its 4 year history.  find something better to do, trolls.

**Comment by Giovani-Brady** [comment]
As always, appreciate the lesson @jaymedavis

**Comment by jaymedavis** [comment]
also @drewid - if you want to have the latest version of stripe.net along with your changes, you can rebase stripe.net back into your branch (until this gets merged). :)

the purpose of having this open source is so users can fork this and use their own copies - so feel free to do that. 

again - thanks for your work and for the effort to follow existing naming conventions. :)

**Comment by jaymedavis** [comment]
I'm slowly working on getting some of this integrated into the library. There is a lot of changes here, not just managed accounts. I saw a reference to file uploads and parsing the payload via the body which changes how every single call in stripe.net is made. There is lots of good bits in here for me to pick from, but it will take awhile to slowly get this pulled in and tests written.

**Comment by jaymedavis** [comment]
I've started to slowly break this down a bit. Currently, I'm working on merging in your changes with relation to the Account entities. There's been a few things I've had to change like some nullable properties that shouldn't be nullable, etc... but I'm making headway. The plan is to finish the account entities to match the Stripe docs and get that released. Since there is so much to verify and test in this PR, I will take a slow approach with it and get things released as I go through them. I will close the other issue relating to Managed Accounts, and use this PR as the working issue/PR.

**Comment by jaymedavis** [comment]
I just released the StripeAccount entity and all supporting entities for this PR. There were some things I had to fix... a lot of classes did not need to be inherited from StripeObject, that is only when they have an Id. There were a few other properties that were implemented a little differently (such as a copy of the StripeList class) that I cleaned up. Right now external accounts returns a StripeList<dynamic>, because it can be cards or accounts. You can diff the results if you are interested for all of the fixes. Thanks @drewid, @matthewcorven, @mathieukempe, and @odanchak for all of the work getting this going. I used a little bit of everyone's branch. :+1:

Still not complete, but a big step closer.

**Comment by PsyTae** [comment]
Where are we at on this Pull Request?  I can't wait to use Managed Accounts in Stripe.net!

**Comment by jaymedavis** [comment]
This has been added. A couple of small things still left, documented in the release notes:  https://github.com/jaymedavis/stripe.net/releases/tag/v5.3.0, but it's pretty much done. I hope this gives most users everything they need.

I'm leaving this pull request open for now, there's a few other things I want to review before closing it.

**Pull request closed without merging**
