### PR TITLE
Stripe Card Service API Endpoint Updates to support CRUD operations of Recipient Debit Cards

### PR DESCRIPTION
**Pull request by Giovani-Brady**
Makes Stripe API Endpoints available for recipient card creation, retrieval, listing, updating, and deleting.

### CODE REVIEW

**Comment by jaymedavis** [comment]
Recipients now support creating and updating bank accounts and cards. Can you point me to the documentation on stripe's site so I can learn more about this?

**Comment by Giovani-Brady** [comment]
https://stripe.com/docs/api#create_card observe on the right hand side just above the definition there is a toggle between "Customer" and "Recipient"

**Comment by jaymedavis** [comment]
AH. I never caught that. :)

Does this pull request address everything for this? Can the other issues be closed or are they unrelated?

**Comment by Giovani-Brady** [comment]
The two pull requests are directly related but can be integrated separately. this pull requests is for debit card management, the other is for transfers into debit cards. these two updates to 2.7.0 make it a much more complete and whole package. now we can brag that we fully support all basic forms of e-payment.

**Comment by jaymedavis** [comment]
haha. Thanks!

**Comment by jaymedavis** [comment]
what about #280 ? is that addressed in one of the two pull requests?

**Comment by jaymedavis** [comment]
Thanks, I think I finally get it. :+1: 

Btw, I lol'd at your spelling of recipient in the code as a parameter. I spell that word right 1 out of 20 times. :)

**Comment by Giovani-Brady** [comment]
yeah, I've got a horrible spelling problem lol

**Comment by Giovani-Brady** [comment]
Yes Issue #280 is addressed in Pull Request #281

**Comment by Giovani-Brady** [comment]
Note: there was a bug, missed the "/" at the beginning of the Recipients end point API. updated and fixed.

**Comment by jaymedavis** [comment]
it looks like this is really the exact same code, just hits a different endpoint. I might try to find a way to do it a little easier, but starting from your code. (something like having the methods share a single method and passing the either recipient or customer). It seems like some duplication could be fixed. But that's really small, this is plenty to get me started. Thanks again.

**Comment by jaymedavis** [comment]
Let me know if anything else is missing in the library for your use! I'd love to hear about what you are building too sometime if you wouldn't mind sharing. jaymedavis@gmail.com if you want to share. :)

**Comment by Giovani-Brady** [comment]
Updated the implementation to be backwards compatible. Let me know what you think.

**Comment by jaymedavis** [comment]
I don't have a lot of time during the workday to look into this, but from a quick glance it looks awesome. :)

**Comment by jaymedavis** [comment]
Is this the last thing missing in the library for it to be full-purpose for you?

**Comment by Giovani-Brady** [comment]
I believe so. It's fine, I'm using a build from a fork for now. I'd rather the code go through your usual process then be expedited with bugs and errors.

**Comment by jaymedavis** [comment]
Thanks man, that gave me a big smile. :)

**Comment by jaymedavis** [comment]
Couple things here I changed - wanted to check with you to make sure it should be fine:

1) CustomerCards is no longer trailing with /cards, looks like they changed it to sources

        public static string CustomerCards
        {
            get { return BaseUrl + "/customers/{0}/sources"; }
        }

2) I changed stripeId to customerOrRecipientId - I thought it was just a little more intuitive.

**Comment by jaymedavis** [comment]
On second thought, I'll probably just stick with /cards. If it works, it works. It would be ideal to talk with stripe about this though. 

Also I changed IsNullOrWhitespace to IsNullOrEmpty, since that method didn't exist.

**Comment by Giovani-Brady** [comment]
IsNullOrWhitespace was introduced as part of the 4.0 .Net framework so the Stripe3.5 project may not compile correctly but the Stripe project targeting the latest framework will compile correctly.

Recommend we use both where appropriate as IsNullOrWhitespace is the replacement for IsNullOrEmpty.

Yes it seems the API endpoint has been updated from "cards" to "sources" with the latest version of the API. It's been updated everywhere but the Retrieve A Card API endpoint has "cards" instead of the new "sources". It would be worth a quick email to verify that the change is global and also shed some light on backwards compatibility "cards" vs "sources"

Also I thought this package had a hard coded version of the API in the project? has this been updated?

**Comment by jaymedavis** [comment]
It still has a hardcoded version of the API in StripeConfiguration - so as long as I don't update that, we should be ok for now with cards. I will release this before I release those updates anyway.

I think i'll stick with IsNullOrEmpty for now. I agree the other is preferable (for the obvious reason it catches whitespace), but the only way around that right now is to to some #if statements in the code, and that makes it a mess. The way the 3.5 project is setup right now, there is no way to have a separate file for each version, it's just #if blocks.

**Comment by jaymedavis** [comment]
Ok, this is all checked in locally and will be part of the next release. I updated the readme as well, to let users know that isRecipient is optional now too. Thanks for the help!

**Comment by Giovani-Brady** [comment]
No problem, let me know if there's anything else hanging to the way side. I'd like to be a regular contributor.

**Pull request closed without merging**
