### PR TITLE
Adding Product/SKU/Order support

### PR DESCRIPTION
**Pull request by daniel-cohen**

### CODE REVIEW

**Comment by daniel-cohen** [comment]
FYI: This is still work in progress.

**Comment by jaymedavis** [comment]
why close??

**Comment by daniel-cohen** [comment]
@jaymedavis I'll check in a few more things today and re-open it. There nothing wrong with it.

**Comment by daniel-cohen** [comment]
@jaymedavis ,Have a look at "INestedNamedOptions", I've created it as a replacement for "INestedOptions" because I wanted to be able to use the same nested objects with different property names.
I haven't touched your existing classes implementing "INestedOptions" though.

**Comment by jaymedavis** [comment]
Can you give me an example of how this would be used? I'm a little confused in how it works with the string it applies (INestedNamedOptions)


Also - be sure to rebase / merge latest as soon as you can. I'm currently working on refactoring a lot with the parameter builder. The plan is instead of working on different methods, I want to make it work like a plugin type system - 

So like ...   lets say there is an interface that takes a property, the existing requestString and processes it - then the ParameterBuilder can become middleware and be eaiser to read.

So the part in parameter builder that parses date filtering, becomes it's own plugin...
```class DatePlugin : IAttributeParserPlugin {
  string Process(...)
  {
    return requestString;
  }
}```

So then the parameter builder method comes out like...
```
public ApplyAllParameters() {
   var plugins = AttributePluginManager.GetPlugins();
   foreach(plugin in plugins)
     plugin.Process();
} 
```

then there will be a folder full of plugins which follow a standard for how to process parameters - metadata plugins, date plugins, you name it. Then we just parse all the plugins when building the requestString. I'm trying to comment this class to make it explained better too - but you seem to grok that just fine anyway. 

I'm not sure how it will end up looking, I'm just sharing my ideas with you since you've done so much work. 

Thanks

**Comment by daniel-cohen** [comment]
@jaymedavis Let me know if you want to have a chat about these things. I left you DM on twitter.
I think using plugins for the parsing is a good idea.

Some notes:
1. I created INestedNamedOptions to avoid having to define the full name pass to stripe on the nested object.
E.g: instead of specifying [JsonProperty("source[account_holder_name]")] on the  SourceBankAccount.AccountHolderName property, I will only specifying [JsonProperty("account_holder_name")].
and [JsonProperty("source")] on the BankAccountCreateOptions.SourceBankAccount property.

2.  There's no need to iterate through multiple "JsonPropertyAttribute" for each property because "JsonPropertyAttribute " is declared as AllowMultiple = false

3. I left your handling of "StripeDateFilter", but I think it can handle in a similar way to what I've done with everything else(I recursively build the parameter names).

TODO:
1. In updates, you have to allow passing null/empty values because it can clear example. E.g: The metadata field in Update order.
That's why I've added a "includeEmptyValues" parameter to "ApplyParameters".
2. There are a few fields I left out.


I'm re-opening the PR now and letting you review it as is because I have no more time to spend on it right now.

Thanks for all your work !

**Comment by daniel-cohen** [comment]
@jaymedavis Let me know if you want to have a chat about these things. I left you DM on twitter.
I think using plugins for the parsing is a good idea.

Some notes:
1. I created INestedNamedOptions to avoid having to define the full name pass to stripe on the nested object.
E.g: instead of specifying [JsonProperty("source[account_holder_name]")] on the  SourceBankAccount.AccountHolderName property, I will only specifying [JsonProperty("account_holder_name")].
and [JsonProperty("source")] on the BankAccountCreateOptions.SourceBankAccount property.

2.  There's no need to iterate through multiple "JsonPropertyAttribute" for each property because "JsonPropertyAttribute " is declared as AllowMultiple = false

3. I left your handling of "StripeDateFilter", but I think it can handle in a similar way to what I've done with everything else(I recursively build the parameter names).

TODO:
1. In updates, you have to allow passing null/empty values because it can clear example. E.g: The metadata field in Update order.
That's why I've added a "includeEmptyValues" parameter to "ApplyParameters".
2. There are a few fields I left out.


I'm re-opening the PR now and letting you review it as is because I have no more time to spend on it right now.

Thanks for all your work !

**Comment by jaymedavis** [comment]
I definitely understand having little time! Understanding INestedNamedOptions now - I like it very much. :)

Thanks so much for all of your contributions @daniel-cohen. This is great stuff.

**Comment by daniel-cohen** [comment]
@jaymedavis Will you be able to merge this + #525 for the next release ?
RE: This PR, I think you just need to decide what to do with "ParameterBuilder".

**Comment by jaymedavis** [comment]
The parameter builder is going to change a lot, so those pieces wont make it in soon. I need to figure out what the differences are (the file changes tab isn't very helpful in this case), and get that added. The product/sku stuff is more straightforward, but a Stripe field engineer was working on this as well, so I will need to catch up with Stripe on this first. 

Everything will eventually make it in, but my time is limited. It will probably have to go in a few pieces at a time.

**Comment by jaymedavis** [comment]
One small thing to remove from this - Stripe comments/documentation change all the time, so that's why I haven't added any xml comments to classes right now. I might do this later, but for now it's just a maintenance nightmare.

**Comment by WaqasRL** [comment]
Hi
Any ETA we shall get these changes in a new release?

**Comment by WaqasRL** [comment]
@jaymedavis what do you think when we can have these changes in a new release? need this badly.. :)

**Comment by jaymedavis** [comment]
I am working on items as soon as I can. This particular PR is in pretty good shape - it needs the documentation removed and to use the StripeBasicService. If you want to do some of the work, let me know and I can setup a branch for you.

**Comment by jaymedavis** [comment]
I've had some things come up that I've had to knock out before I could get back to PR's - any help appreciated, so let me know if you are working on anything. Otherwise, I should get started on this within a couple of weeks. That's my best guess. :)

**Comment by aschaible** [comment]
Any new updates here?  Would love to use this feature.

**Comment by aschaible** [comment]
It looks like the structure has changed a decent amount.  I'm working on a PR to @daniel-cohen to update his code to fit in the new structure.

**Comment by jaymedavis** [comment]
That's been one of the blocks. This should also use the StripeBasicService<> most likely. I got rid of a lot of that cookie cutter code.

**Comment by aschaible** [comment]
@jaymedavis Do you still want the xml-doc removed?

**Comment by jaymedavis** [comment]
@aschaible it would need to be updated from when this PR was created, but I'm not against it - I've started adding them as well.

**Comment by daniel-cohen** [comment]
@aschaible thanks for picking this up! I didn't have time to update/maintain the PR.

**Comment by aschaible** [comment]
@daniel-cohen No problem -- however I had a lot of trouble merging master into your PR, so I just started fresh.  Want me to send a PR your way so  that to you so you can re-submit this?  I mostly just copied your code so I want to make sure you get the credit :)

**Comment by daniel-cohen** [comment]
@aschaible I can add you as a collaborator and you can can update the "product-support" branch or even create a new branch + PR in to "product-support" .
This way if you need to make changes they'll go into this PR too.
And also, you'll get the credit too ;)

**Comment by jaymedavis** [comment]
You guys are great. :)

Feel free to send smaller pieces over, that's easier for me anyway. If we have just an entity or two without the service yet, that's fine to merge in. It's easier for me to verify small pieces anyway. Daniel's entities may still be fine, I just want this to use the StripeBasicService (search all for example). Anything working with the internals might have changed a lot due to the new plugin based parsing as well. Hope this helps!

**Comment by aschaible** [comment]
@jaymedavis I checked all of the entities and they looked good.  I also updated the services to use StripeBasicService and changed some of @daniel-cohen 's method names to be inline with the new names (some common names existed in both StripeBasicService and specific implementations).  That made it more clear - also some had the same names and method signature so it was recursive.

Example PR is here for review:  https://github.com/jaymedavis/stripe.net/pull/744

**Comment by jaymedavis** [comment]
Going to implement via #744, as that was updated to contain these bits and the new infrastructure.

**Pull request closed without merging**
