### PR TITLE
updated closed and forgiven properties of the StripeInvoice object to be nullable

### PR DESCRIPTION
**Pull request by Giovani-Brady**
address #292

ready for code review

### CODE REVIEW

**Comment by jaymedavis** [comment]
This is related to #296. There may be other places (creating an invoice) that also need this change. Will address in next release.

**Comment by Giovani-Brady** [comment]
the first commit did address the scenario when creating an invoice, the additional commit addresses the scenario when updating an invoice.

ready for code review.

**Comment by Giovani-Brady** [comment]
discard and disregard all my contributions. i thought this was an open source repository.

**Comment by jaymedavis** [comment]
This still needs to be pulled in - ?

**Pull request closed without merging**
