### PR TITLE
Const string of all Event Types

### PR DESCRIPTION
**Pull request by jt000**
Adding constant strings defining all possible stripe event types as defined at https://stripe.com/docs/api#event_object. I found this incredibly helpful so I don't have to keep looking them up online & thought you might want to add it to Stripe.Net...

### CODE REVIEW

**Comment by jaymedavis** [comment]
cool - will look into this more when I get the chance. :)

As for the XML comments, commenting and documentation will be part of a pro release of stripe.net (not a free version), so I wont include that part.

**Comment by jt000** [comment]
"pro release" of stripe.net?! I have to admit this worries me a bit. After the Seahawks loss last night I don't know how much more heartbreak I can take... :)

Have you created any documentation on this that I could read up on? (prices, benefits, what happens to the "free" version of stripe.net, etc)

**Comment by jaymedavis** [comment]
haha. I wanted Seattle to win too. Titans fan, but I can't stand the Pats or Brady.

The "pro release" will contain documentation and maybe some admin UI stuff for logging, etc. The free/open source version will not change. It will be a freemium model, so having the open source library stellar is an important part. No pricing yet. Probably somewhere between $99 and $199 (dont quote me), but it wont do anything the open source library wont do. You would even be able to build in the licensed version (to make your life easier) and deploy with the open source version. At least, that's the plan right now. 

No documentation, all this was just considered in the past few weeks. Stripe.net takes up a BIG part of my time. The users have been wonderful and the comments about the library have been humbling.

**Comment by jaymedavis** [comment]
Really curious what your reaction is to this? :)

**Comment by jt000** [comment]
I've moved this out of my companies repository & into my personal ones. I'll resubmit this pull request

**Pull request closed without merging**
