### PR TITLE
Added Proration Date to StripeSubscriptionUpdateOptions

### PR DESCRIPTION
**Pull request by mixtmeta**
For #524

### CODE REVIEW

**Comment by jaymedavis** [comment]
can you tell me your method for testing this? I'm working on a test for this in stripe.net - thanks.

**Comment by jaymedavis** [comment]
I talked to Stripe about this, because I was unable to see anything working from testing. So how prorate works, is if you just set prorate or the proration date, it will actually not do anything at all. Something else has to change. I am going to get the other properties added for subscription updates so this wont happen, but it's something to be aware of.

**Comment by jaymedavis** [comment]
this is complete. It was a bit tricky to test due to how the proration works, but it will be in the next release - thanks much - your code worked perfectly.

**Comment by mixtmeta** [comment]
Thanks. To test I compiled a local version of the project with the change in it and dumped it into a project I was working on that required proration. Then I checked the stripe log via the dashboard to make sure the proration_date field was received as part of my request.

**Comment by joshpierce** [comment]
@jaymedavis do you have an estimate on when the next release will be that would include this?

We're using stripe.net (and <3 it) and are looking to use this feature as we're currently using the prorate date on our generation of upcoming invoice for previewing a subscription change.

Cheers!

**Comment by jaymedavis** [comment]
Hi @joshpierce - sometime over the next few days I hope to get a release out. There are a couple more things I'm looking at - including a recent PR to get upcoming invoice lines (with pagination).

**Pull request merged**
