### PR TITLE
[PCI / Security] Never create a token server-side

### PR DESCRIPTION
**Pull request by matthewarkin**
In regards to PCI compliance creating a token server side and saving a token server-side are equivalent in scope. Tokens should only be made client side using Stripe.js or Stripe Checkout.

Your server should never have access to card data beyond the last 4 and expiration

### CODE REVIEW

**Comment by jaymedavis** [comment]
This is not entirely accurate. While client side is typically the recommended approach, it is possible to have your own servers pass and create the token and be PCI compliant. There are various security protocols that need to be in place, but it is entirely possible. The client side approach is the recommended approach - that's why there is a big video on the readme for how to do it, but it is also possible to be PCI compliant via server traffic.

**Comment by matthewarkin** [comment]
I'm not saying it isn't but when a user is new to PCI compliance and Stripe, they just see your docs, and copy and paste code and they think they can just access card data server-side. The easiest level of PCI compliance (SAQ A or A-EP) would be no server-side access. With SAQ D, server-side access and server-side storage is the same SAQ. 

Personally I'd update all the docs to just show token examples.

Also it makes no sense to make a token server-side since they just last for 5 minutes, if you're going to make a token server-side, you should just send the card data to the customers API or to the charges API.

**Comment by praboud** [comment]
@jaymedavis: I think it's entirely reasonable to document the fact that you can create tokens from stripe.net, as there is a valid use for this in tests. However, the documentation should come with the caveat that this is _only_ appropriate for use in test mode (where you want to test code which in production would take a token from stripe.js as input).

Using serverside tokenization in production provides absolutely no compliance value (or actual security benefits). If I really want to pass cards through my server, I should just bite the bullet and pass the card directly. Using serverside tokenization like this is just cargo cult code.

This distinction isn't currently captured in the documentation, and I think is potentially a pitfall for new users. If you think this is reasonable, I'd be happy to draft up a blurb documenting the above.

**Comment by jaymedavis** [comment]
I would be fine with a caveat that this is only valuable if your server is PCI compliant. I'm also fine with saying if you are PCI compliant, you may not want to deal with tokens at all and just pass them directly with ephemeral storage. I'm sure there may be cases of nieve copy/paste from some users that don't understand the consequences, but there's also cases of people that have dealt with PCI compliance for a long time. :)

I closed this request because I believed simply deleting the code from the readme was not the right solution.

**Pull request closed without merging**
