### PR TITLE
Fraud updates

### PR DESCRIPTION
**Pull request by AndiTheBusinessman**
The library was missing fraud checks, and with the amount of fraud happening right now, it's time to change that!

Therefore, I have added a simple StripeFraudDetails class and updated StripeChargeUpdateOptions to
allow user FraudDetails to be added. 

StripeCharge now returns StripeFraudDetails.

### CODE REVIEW

**Comment by jaymedavis** [comment]
Thanks, Andi! Where did you find the documentation for how this works? Somehow I missed it. :)

I'll write a test for this and get it merged asap, thanks again!

**Comment by AndiGladwin** [comment]
Hi Jayme. It's in the Stripe documentation. Although, I tend to just favour
viewing the JSON in their logs and making things work!

I hope you can use this as I'd much prefer to use the Nuget installation
that roll my own!

--Andi

**Comment by jaymedavis** [comment]
This is done, will be checking in today. I made this work exactly like Metadata, so it was familiar- here is the test to show you an example... (a charge has to be refunded before you can mark it fraudulent)

```
using System.Collections.Generic;
using Machine.Specifications;

namespace Stripe.Tests
{
    public class when_refunding_and_setting_fraud_details
    {
        private static StripeChargeCreateOptions _stripeChargeCreateOptions;
        private static StripeCharge _stripeCharge;
        private static StripeChargeService _stripeChargeService;
        private static StripeChargeUpdateOptions _stripeChargeUpdateOptions;

        Establish context = () =>
        {
            _stripeChargeService = new StripeChargeService();
            _stripeChargeCreateOptions = test_data.stripe_charge_create_options.ValidCard();

            // create a charge
            _stripeCharge = _stripeChargeService.Create(_stripeChargeCreateOptions);

            // refund the charge
            new StripeRefundService().Create(_stripeCharge.Id);

            // create charge update options to set the charge as fradulent
            _stripeChargeUpdateOptions = new StripeChargeUpdateOptions
            {
                FraudDetails = new Dictionary<string, string>
                {
                    { "user_report", "fraudulent" }
                }
            };
        };

        Because of = () =>
            _stripeCharge = _stripeChargeService.Update(_stripeCharge.Id, _stripeChargeUpdateOptions);

        It should_have_fraud_details = () =>
            _stripeCharge.FraudDetails.ShouldEqual(_stripeChargeUpdateOptions.FraudDetails);
    }
}
```

**Comment by arielcloud** [comment]
thanks!

**Comment by jaymedavis** [comment]
you're welcome :)

**Pull request closed without merging**
